site_name: primal-page

repo_url: https://github.com/ChrisgKent/primal-page
repo_name: primal-page

site_url: https://chrisgkent.github.io/primal-page/
theme:
  name: material

nav:
  - Overview: index.md
  - Command Line Interface: cli.md
  - Examples: examples.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
